### ISSUE TITLE
Gradle errors when run sonarlint tasks

### ISSUE THREAD

**Issue by catostrophe** [Lucas3oo/sonarlint-gradle-plugin#2]
Gradle v7.5.1
sonarlint-gradle-plugin v1.0.0-beta.5

When I run `:sonarlintMain` Gradle shows a lot of errors that still don't affect the build.

<details>
<summary>output</summary>

Errors occurred while build effective model from /root/.gradle/caches/modules-2/files-2.1/org.eclipse.platform/org.eclipse.core.resources/3.18.0/517a3c05e78707f1bbff4583c7bc2de12c167ca8/org.eclipse.core.resources-3.18.0.pom:
'modelVersion' must be one of [4.0.0] but is '4.0'. in org.eclipse.platform:org.eclipse.core.resources:3.18.0
Errors occurred while build effective model from /root/.gradle/caches/modules-2/files-2.1/org.eclipse.platform/org.eclipse.core.runtime/3.26.0/1e185dcbb0dfbd81f2cd8f61b7ba98eb0566336a/org.eclipse.core.runtime-3.26.0.pom:
'modelVersion' must be one of [4.0.0] but is '4.0'. in org.eclipse.platform:org.eclipse.core.runtime:3.26.0
Errors occurred while build effective model from /root/.gradle/caches/modules-2/files-2.1/org.eclipse.platform/org.eclipse.osgi/3.18.100/c62edc95892e837c57f020c698d2bc82c6714d2d/org.eclipse.osgi-3.18.100.pom:
'modelVersion' must be one of [4.0.0] but is '4.0'. in org.eclipse.platform:org.eclipse.osgi:3.18.100
Errors occurred while build effective model from /root/.gradle/caches/modules-2/files-2.1/org.eclipse.platform/org.eclipse.equinox.common/3.16.[200](https://gitlab.c24.local/open-processing-platform/functions/base/jvm/common/-/jobs/461284#L200)/68be1223dba8d8d87277bcfc4684cea66c673d3a/org.eclipse.equinox.common-3.16.200.pom:
'modelVersion' must be one of [4.0.0] but is '4.0'. in org.eclipse.platform:org.eclipse.equinox.common:3.16.200
Errors occurred while build effective model from /root/.gradle/caches/modules-2/files-2.1/org.eclipse.platform/org.eclipse.core.jobs/3.13.100/9f532284ebca584d41c9b8e182343f2ee2d4c977/org.eclipse.core.jobs-3.13.100.pom:
'modelVersion' must be one of [4.0.0] but is '4.0'. in org.eclipse.platform:org.eclipse.core.jobs:3.13.100
Errors occurred while build effective model from /root/.gradle/caches/modules-2/files-2.1/org.eclipse.platform/org.eclipse.equinox.preferences/3.10.100/43fe3c49d5a6a30090b7081015e4a57bd0a6cb98/org.eclipse.equinox.preferences-3.10.100.pom:
'modelVersion' must be one of [4.0.0] but is '4.0'. in org.eclipse.platform:org.eclipse.equinox.preferences:3.10.100
Errors occurred while build effective model from /root/.gradle/caches/modules-2/files-2.1/org.eclipse.platform/org.eclipse.core.contenttype/3.8.200/e2fdb068262514474d73f236adaa821d9c861786/org.eclipse.core.contenttype-3.8.200.pom:
'modelVersion' must be one of [4.0.0] but is '4.0'. in org.eclipse.platform:org.eclipse.core.contenttype:3.8.200
Errors occurred while build effective model from /root/.gradle/caches/modules-2/files-2.1/org.eclipse.platform/org.eclipse.text/3.12.200/3a81eddfd0e8756cbdd23dd24b23f92e1cc6bb4c/org.eclipse.text-3.12.200.pom:
'modelVersion' must be one of [4.0.0] but is '4.0'. in org.eclipse.platform:org.eclipse.text:3.12.200

</details>

What may be the reason for this?

**Comment by Lucas3oo** [comment]
Hi
I have kind of heard this too at some point but I can't reproduce it. My suspicion is that some of the Eclipse dependencies don't have the correct meta data. 

The plugin itself, nor the lib from Sonar have any dependencies to Eclipse.
The plugin isn't doing any meta data resolving either.

So if you can provide some sample project where you get this issue I will be super happy.
Or at least if you know some other plugin that you have that might infer in some way. Maybe Spotless? It uses Eclipse jars for formatting rules.

**Comment by Lucas3oo** [comment]
org.eclipse.core.resources-3.18.0.pom seems to be from Sep 13 so I think that some of the dependencies are just using "latest" as version they depend on and all of the sudden you got a newer org.eclipse.core.resources lib that isn't properly published.

Check with some of the cradle tasks what dependencies you have in the project. Then you can perhaps backtrace which lib is using Eclipse and alter that to fix the version to some older version of org.eclipse.core.resources etc.

**Comment by Lucas3oo** [comment]
The grgit plugin is also using Eclipse JARs so maybe the issue is with that plugin's dependencies.

**Comment by catostrophe** [comment]
See: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/461

Sonar depends on eclipse.jdt.core

**Comment by Lucas3oo** [comment]
Same issue with org.eclipse.platform:org.eclipse.core.expressions:3.8.200, see 
https://github.com/eclipse-platform/eclipse.platform/issues/180
