### ISSUE TITLE
sonar-java-plugin 7.22.0.31918 doesn't find any issues

### ISSUE THREAD

**Issue by alok-runner** [Lucas3oo/sonarlint-gradle-plugin#5]
`sonarlintPlugins 'org.sonarsource.java:sonar-java-plugin:7.22.0.31918'` doesn't find any smells or bugs, where it was finding hundreds before in `7.20.0.31692`

**Comment by Lucas3oo** [comment]
Seems that that version of the plugin can't be used with Sonarlint. 

I got this in the log:
```
2023-07-25T16:22:55.468+0200 [DEBUG] [org.gradle.api.Task] Plugin 'Java Code Quality and Security' requires plugin API 9.9 while SonarLint supports only up to 8.9. Skip loading it.
```

I shall see if I can improve the error handling around how the loading of the plugins to catch this so the user can be notified.

**Comment by alok-runner** [comment]
thanks, it would be helpful if the task fails so that my CI pipeline fails this upgrade

**Comment by Lucas3oo** [comment]
Fixed in release 1.0.0-beta.17

**Comment by catostrophe** [comment]
@Lucas3oo Why do you still use the outdated `org.sonarsource.sonarlint.core:sonarlint-core:8.0.2.42487` while the latest version is [9.6.1.76766](https://mvnrepository.com/artifact/org.sonarsource.sonarlint.core/sonarlint-core/9.6.1.76766)?

It prevents us from upgrading the sonar-java-plugin.

**Comment by Lucas3oo** [comment]
The API in 9.6 is quite different so I did a stab on it but didn't get that far. I will look into this once more.
Cheers
Lucas

**Comment by Lucas3oo** [comment]
Happy to say that it wasn't that much work after all. So enjoy: version 2.0 of the plugin which works with sonarlint core 9.6; https://plugins.gradle.org/plugin/se.solrike.sonarlint
