### ISSUE TITLE
sourceCompatibility is read before configuration is complete

### ISSUE THREAD

**Issue by chrisribble** [Lucas3oo/sonarlint-gradle-plugin#9]
Versions `1.0.0-beta.16` through `2.0.0` incorrectly use the version of the Java from the JRE running Gradle when specifying the Java source level to use with Sonarlint.

For example, running `./gradlew build` on this project with a Java 21 JRE enables the rules [`java:S6204`, `java:S6126`] and causes the build to fail.

Running on one of my team's projects with `./gradlew sonarlintMain --debug` I observed that the `sonar.java.source` property was being set to 21 when I run it with Java 21, despite having a configuration like the following in `build.gradle`:
```groovy
java {
   sourceCompatibility = JavaVersion.VERSION_17
   targetCompatibility = JavaVersion.VERSION_17
}
```

Looking at the history, it appears that this was broken by `c875ae86126af9798e1b7f861f7c6290dd8c1aed`. Moving the read of `sourceCompatibility` from the `SonarlintAction` constructor back to the `analyze` function fixes it: I tested publishing locally and running against my project and see that the correct version is set in `sonar.java.source`.

I didn't dig much deeper, but presumably the issue here is that reading `sourceCompatiblity` in the constructor ends up reading a default value configured by the `java` plugin _before_ the project's configuration has been applied.

**Comment by Lucas3oo** [comment]
Thanks a lot for the finding!
